// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var engSubProjectList = EngSubProjectList.FromJson(jsonString);

namespace QuickType
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class EngSubProjectList
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("userID")]
        public Guid UserId { get; set; }

        [JsonProperty("projectID")]
        public long ProjectId { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("remark")]
        public string Remark { get; set; }

        [JsonProperty("deadline")]
        public DateTimeOffset Deadline { get; set; }

        [JsonProperty("manHours")]
        public long ManHours { get; set; }

        [JsonProperty("progressFraction")]
        public long ProgressFraction { get; set; }

        [JsonProperty("priorityLevel")]
        public long PriorityLevel { get; set; }

        [JsonProperty("isActive")]
        public bool IsActive { get; set; }

        [JsonProperty("user")]
        public User User { get; set; }

        [JsonProperty("project")]
        public object Project { get; set; }
    }

    public partial class User
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("id")]
        public Guid Id { get; set; }

        [JsonProperty("userName")]
        public string UserName { get; set; }

        [JsonProperty("normalizedUserName")]
        public string NormalizedUserName { get; set; }

        [JsonProperty("email")]
        public string Email { get; set; }

        [JsonProperty("normalizedEmail")]
        public string NormalizedEmail { get; set; }

        [JsonProperty("emailConfirmed")]
        public bool EmailConfirmed { get; set; }

        [JsonProperty("passwordHash")]
        public string PasswordHash { get; set; }

        [JsonProperty("securityStamp")]
        public string SecurityStamp { get; set; }

        [JsonProperty("concurrencyStamp")]
        public Guid ConcurrencyStamp { get; set; }

        [JsonProperty("phoneNumber")]
        public string PhoneNumber { get; set; }

        [JsonProperty("phoneNumberConfirmed")]
        public bool PhoneNumberConfirmed { get; set; }

        [JsonProperty("twoFactorEnabled")]
        public bool TwoFactorEnabled { get; set; }

        [JsonProperty("lockoutEnd")]
        public object LockoutEnd { get; set; }

        [JsonProperty("lockoutEnabled")]
        public bool LockoutEnabled { get; set; }

        [JsonProperty("accessFailedCount")]
        public long AccessFailedCount { get; set; }
    }

    public partial class EngSubProjectList
    {
        public static EngSubProjectList[] FromJson(string json) => JsonConvert.DeserializeObject<EngSubProjectList[]>(json, QuickType.Converter.Settings);
    }

    public static class SerializeEngSubProject
    {
        public static string ToJson(this EngSubProjectList[] self) => JsonConvert.SerializeObject(self, QuickType.Converter.Settings);
    }

    internal static class ConverterEngSubProject
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
