// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var engUpcomingProjectListDto = EngUpcomingProjectListDto.FromJson(jsonString);

namespace QuickType
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class EngUpcomingProjectListDto
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("assigedUserId")]
        public Guid AssigedUserId { get; set; }

        [JsonProperty("deadline")]
        public DateTime Deadline { get; set; }

        [JsonProperty("code")]
        public string Code { get; set; }

        [JsonProperty("remark")]
        public string Remark { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("customer")]
        public string Customer { get; set; }

        [JsonProperty("isNotified")]
        public bool IsNotified { get; set; }

        [JsonProperty("user")]
        public AssigedUser AssigedUser { get; set; }
    }

    public partial class AssigedUser
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("id")]
        public Guid Id { get; set; }

        [JsonProperty("userName")]
        public string UserName { get; set; }

        [JsonProperty("normalizedUserName")]
        public string NormalizedUserName { get; set; }

        [JsonProperty("email")]
        public string Email { get; set; }

        [JsonProperty("normalizedEmail")]
        public string NormalizedEmail { get; set; }

        [JsonProperty("emailConfirmed")]
        public bool EmailConfirmed { get; set; }

        [JsonProperty("passwordHash")]
        public string PasswordHash { get; set; }

        [JsonProperty("securityStamp")]
        public string SecurityStamp { get; set; }

        [JsonProperty("concurrencyStamp")]
        public Guid ConcurrencyStamp { get; set; }

        [JsonProperty("phoneNumber")]
        public string PhoneNumber { get; set; }

        [JsonProperty("phoneNumberConfirmed")]
        public bool PhoneNumberConfirmed { get; set; }

        [JsonProperty("twoFactorEnabled")]
        public bool TwoFactorEnabled { get; set; }

        [JsonProperty("lockoutEnd")]
        public object LockoutEnd { get; set; }

        [JsonProperty("lockoutEnabled")]
        public bool LockoutEnabled { get; set; }

        [JsonProperty("accessFailedCount")]
        public long AccessFailedCount { get; set; }
    }

    public partial class EngUpcomingProjectListDto
    {
        public static EngUpcomingProjectListDto[] FromJson(string json) => JsonConvert.DeserializeObject<EngUpcomingProjectListDto[]>(json, QuickType.Converter.Settings);
    }

    public static class SerializeEngUpcomingProject
    {
        public static string ToJson(this EngUpcomingProjectListDto[] self) => JsonConvert.SerializeObject(self, QuickType.Converter.Settings);
    }

    internal static class ConverterEngUpcomingProject
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
