// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var loginValuesDto = LoginValuesDto.FromJson(jsonString);

namespace HarithaHRMS.DTOs
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class LoginValuesDto
    {
        [JsonProperty("success")]
        public bool Success { get; set; }

        [JsonProperty("message")]
        public string Message { get; set; }

        [JsonProperty("islogedin")]
        public bool Islogedin { get; set; }

        [JsonProperty("username")]
        public string Username { get; set; }

        [JsonProperty("workingHours")]
        public double WorkingHours { get; set; }

        [JsonProperty("userid")]
        public Guid Userid { get; set; }

        [JsonProperty("userreport")]
        public Userreport Userreport { get; set; }
    }

    public partial class Userreport
    {
        [JsonProperty("leaveViewModels")]
        public LeaveViewModel[] LeaveViewModels { get; set; }

        [JsonProperty("date")]
        public DateTimeOffset Date { get; set; }
    }

    public partial class LeaveViewModel
    {
        [JsonProperty("username")]
        public string Username { get; set; }

        [JsonProperty("todayWorkedHoursProgress")]
        public double TodayWorkedHoursProgress { get; set; }

        [JsonProperty("monthWorkedHoursProgress")]
        public double MonthWorkedHoursProgress { get; set; }

        [JsonProperty("monthIdleHours")]
        public long MonthIdleHours { get; set; }

        [JsonProperty("dailyIdleHours")]
        public long DailyIdleHours { get; set; }
    }

    public partial class LoginValuesDto
    {
        public static LoginValuesDto FromJson(string json) => JsonConvert.DeserializeObject<LoginValuesDto>(json, HarithaHRMS.DTOs.Converter.Settings);

    }

    public static class SerializeLogin
    {
        public static string ToJson(this LoginValuesDto self) => JsonConvert.SerializeObject(self, HarithaHRMS.DTOs.Converter.Settings);
    }

    internal static class ConverterLogin
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
